server:
  port: 4000

spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://postgres:${DB_PORT:5432}/${DB_DATABASE_NAME:fu_oj_backend}
  data:
    redis:
      host: redis
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: "*"
          debug: ${EMAIL_DEBUG:false}

minio:
  endpoint: http://minio:${MINIO_PORT:9000}

