name: CI/CD Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/fu-oj
            git pull origin dev

            # Run tests
            echo "Running tests..."
            ./mvnw test || { echo "Tests failed!"; exit 1; }

            # Deploy
            echo "Deploying..."
            docker compose -f docker-compose-uat.yaml --env-file .env.uat up -d --build

            # Bước 2: Health check
            echo "Waiting for service to start..."
            sleep 10

            # Check if container is running
            if ! docker compose -f docker-compose-uat.yaml ps | grep -q "Up"; then
              echo "Container is not running!"
              exit 1
            fi

            # Check health endpoint
            if ! curl -f http://localhost:8080/actuator/health > /dev/null 2>&1; then
              echo "Health check failed!"
              exit 1
            fi

            echo "Deployment successful!"
